# Generated by Django 2.2.3 on 2019-07-23 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_location', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=65)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(max_length=65)),
                ('seats', models.IntegerField()),
                ('color', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Client_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65)),
                ('last_name', models.CharField(max_length=65)),
                ('email', models.CharField(max_length=65)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=65)),
                ('password', models.CharField(max_length=200)),
                ('access', models.CharField(max_length=65)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Clients')),
            ],
        ),
    ]
