# Generated by Django 2.2.3 on 2019-07-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_recordings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vehicles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='stream_feed',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
