# Generated by Django 2.2.3 on 2019-07-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190724_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Client_Users',
            new_name='Client_User',
        ),
        migrations.RenameModel(
            old_name='Recordings',
            new_name='Recording',
        ),
        migrations.RenameModel(
            old_name='Vehicles',
            new_name='Vehicle',
        ),
        migrations.RenameModel(
            old_name='Vehicle_Types',
            new_name='Vehicle_Type',
        ),
    ]
