# Generated by Django 2.2.3 on 2019-07-25 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190724_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('feed', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('tracker_listen', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='stream_feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Camera_Feed'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tracker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Tracker'),
        ),
    ]
