# Generated by Django 2.2.3 on 2019-07-25 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20190725_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='client.Vehicle_Type'),
        ),
    ]
