# Generated by Django 2.2.3 on 2019-07-26 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190725_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='stream_feed',
        ),
        migrations.AddField(
            model_name='camera_feed',
            name='assigned_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Vehicle'),
        ),
    ]
