# Generated by Django 2.2.3 on 2019-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_auto_20190726_1826'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='client_location',
            new_name='company_location',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='client_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='client',
            new_name='company',
        ),
    ]
