# Generated by Django 2.2.3 on 2019-07-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_modelname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelName',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
