# Generated by Django 2.2.3 on 2019-07-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20190726_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera_feed',
            options={'verbose_name_plural': 'Camera Feed'},
        ),
        migrations.AlterModelOptions(
            name='vehicle_type',
            options={'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
