# Generated by Django 2.2.3 on 2019-07-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20190726_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='company_id',
        ),
    ]
